### ISSUE TITLE
ASSET judgements have not been upload?

### ISSUE THREAD

**Issue by DavidNemeskey** [facebookresearch/asset#4]
Hi, the paper mentions two sets of human judgements:
- section 5: rating simplifications in ASSET
- section 6: evaluating metrics

According to the paper, the first setup had the human judges rate the crowdsourced simplifications in ASSET itself. The second is for evaluating metrics on the output of various other systems.

If I understand correctly, only the second dataset has been uploaded to the repository, which is of limited use without access to the systems that generated the simplifications. Or am I missing something? If not, is there any chance the first set of judgements could be uploaded as well? 

Thank you very much.

**Comment by feralvam** [comment]
Hi David! You are right, the human preference judgments have not been released. Unfortunately, I don't seem to be able to find them in my files. @louismartin do you have them?

**Comment by louismartin** [comment]
Hi @DavidNemeskey 
I just dig up my old files and found the pairwise comparisons for section 5, they are [now uploaded here](https://github.com/facebookresearch/asset/blob/main/human_ratings/asset_pairwise_comparisons_with_turkcorpus_and_hsplit.csv).
